-- Migration 002 — Multisender idempotency journal
-- Tracks every individual recipient delivery in a multisend batch.
-- Enables safe resume-on-crash: a recipient whose tx_signature is already
-- recorded (and confirmed on-chain) will not be sent to again.
--
-- Relationship: one multisend_batch has many multisend_deliveries.
-- The batch_id is the tx signature of the first batch transaction (a stable
-- identifier generated client-side before any batch is sent).

create table if not exists multisend_batches (
  id              text        primary key,  -- UUID generated by client before batch starts
  payer_wallet    text        not null,
  token_mint      text        not null,
  total_recipients int        not null,
  created_at      timestamptz default now()
);

create table if not exists multisend_deliveries (
  id              bigserial   primary key,
  batch_id        text        not null references multisend_batches(id),
  recipient       text        not null,
  amount_raw      bigint      not null,     -- raw token units (post-decimal expansion)
  tx_signature    text        unique,       -- set once the tx confirms; null = pending
  confirmed_at    timestamptz,
  created_at      timestamptz default now(),

  -- One (batch, recipient) pair is enough to prevent duplicates within a batch.
  -- We allow the same recipient across different batches (intentional re-airdrops).
  unique (batch_id, recipient)
);

create index if not exists multisend_deliveries_batch_idx on multisend_deliveries (batch_id);
create index if not exists multisend_deliveries_sig_idx   on multisend_deliveries (tx_signature);

-- Comment: to resume a crashed multisend, query:
--   SELECT recipient, amount_raw FROM multisend_deliveries
--   WHERE batch_id = $1 AND tx_signature IS NULL;
-- This returns only the recipients who were not yet confirmed.
